[tools]
bun = "latest"
node = "latest"
"npm:vercel" = "latest"
supabase = "latest"

[env]
NEXT_PUBLIC_ENV = "development"
NEXT_PUBLIC_SUPABASE_URL = {
  value = "http://127.0.0.1:54321",
  redact = true
}
NEXT_PUBLIC_SUPABASE_SECRET_KEY = {
  # hard coded credential used by Supabase in local dev
  value = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0",
  redact = true
}
BIGFIVE_WEB_GITHUB_REPO = "https://github.com/auxesis/bigfive-web"

[tasks."dev"]
dir = "web"
run = "bun run dev"

[tasks."db:start"]
dir = "web"
run = "supabase start"

[tasks."db:stop"]
dir = "web"
run = "supabase stop"

[tasks."db:migrate"]
dir = "web"
run = "supabase migration up"

[tasks."test"]
dir = "web"
env = { NEXT_PUBLIC_ENV = "test" }
run = """
bun run lint
bun run format
bun run test
"""

[tasks."build"]
dir = "web"
run = """
bun run build
"""

[tasks."setup"]
dir = "web"
run = """
bun install
"""
