name: Test bigfive-web
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Inject credentials
        run: |
          cat << EOF > mise.local.toml
          [env]
          NEXT_PUBLIC_SUPABASE_URL = ""
          NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = ""
          EOF
      - uses: jdx/mise-action@v3
        with:
          version: 2026.3.9
          install: true
          cache: true
      - name: Build the app
        run: mise run build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Inject credentials
        run: |
          cat << EOF > mise.local.toml
          [env]
          NEXT_PUBLIC_SUPABASE_URL = ""
          NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = ""
          EOF
      - uses: jdx/mise-action@v3
        with:
          version: 2026.3.9
          install: true
          cache: true
      - name: Run tests
        run: mise run test
